# Generated by Django 2.1.3 on 2018-12-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='암호화폐')),
                ('date', models.DateTimeField()),
                ('open', models.CharField(max_length=200, verbose_name='open')),
                ('high', models.CharField(max_length=200, verbose_name='high')),
                ('low', models.CharField(max_length=200, verbose_name='low')),
                ('close', models.CharField(max_length=200, verbose_name='close')),
                ('volume', models.CharField(max_length=200, verbose_name='volume')),
                ('cap', models.CharField(max_length=200, verbose_name='cap')),
            ],
        ),
    ]
