# Generated by Django 2.1.3 on 2018-12-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='cap',
        ),
        migrations.RemoveField(
            model_name='history',
            name='close',
        ),
        migrations.RemoveField(
            model_name='history',
            name='high',
        ),
        migrations.RemoveField(
            model_name='history',
            name='low',
        ),
        migrations.RemoveField(
            model_name='history',
            name='open',
        ),
        migrations.RemoveField(
            model_name='history',
            name='volume',
        ),
        migrations.AddField(
            model_name='history',
            name='asks',
            field=models.CharField(default=1, max_length=200, verbose_name='asks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='asks_vol',
            field=models.CharField(default=1, max_length=200, verbose_name='asks vol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='bids',
            field=models.CharField(default=1, max_length=200, verbose_name='bids'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='bids_vol',
            field=models.CharField(default=1, max_length=200, verbose_name='bids vol'),
            preserve_default=False,
        ),
    ]
