# Generated by Django 2.1.1 on 2018-09-23 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('subtitle', models.CharField(max_length=100, verbose_name='부제목')),
                ('work_from', models.DateField(blank=True, null=True, verbose_name='기간(시작일)')),
                ('work_to', models.DateField(blank=True, help_text='현재 진행중이면 빈칸', null=True, verbose_name='기간(종료일)')),
                ('now', models.BooleanField(help_text='현재 진행중일 경우 체크', verbose_name='기간(진행중)')),
                ('data', models.TextField(verbose_name='내용')),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=100, verbose_name='이메일')),
                ('profile_img', models.ImageField(upload_to='pf/', verbose_name='프로필사진')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100, verbose_name='분류')),
            ],
        ),
        migrations.AddField(
            model_name='myinformation',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.ResumeType', verbose_name='분류'),
        ),
    ]
