# Generated by Django 2.1.2 on 2018-10-30 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField(verbose_name='테이블 id')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('status', models.CharField(choices=[('deleted', 'status_deleted'), ('notice', 'status_all_notice'), ('normal', 'status_normal')], max_length=20, verbose_name='상태')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(verbose_name='내용')),
                ('up_vote', models.IntegerField(default=0, verbose_name='추천')),
                ('down_vote', models.IntegerField(default=0, verbose_name='비추천')),
                ('ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('down_vote_user', models.ManyToManyField(related_name='down_vote_user', to=settings.AUTH_USER_MODEL)),
                ('up_vote_user', models.ManyToManyField(related_name='up_vote_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
