# Generated by Django 2.1.2 on 2018-10-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('notice', 'status_all_notice'), ('deleted', 'status_deleted'), ('normal', 'status_normal')], max_length=20, verbose_name='상태'),
        ),
    ]
